### ISSUE TITLE
NCBI accession or GFF for specifying genetic features to show with coverage plots

### ISSUE THREAD

**Issue by peterk87** [nhhaidee/wgscovplot#11]
Currently users can only specify a Genbank file with the genetic features that a user would like to highlight. It should be possible to specify an NCBI accession (e.g. MN908947.3) or GFF file instead. Typically, a GFF file is provided for SnpEff variant effect analysis so it would be available locally and most likely in the workflow output directory (e.g. `results/snpeff_db/**/genes.gff`).

If an accession is specified, it should be possible for the tool to use BioPython to pull the necessary info from the NCBI Entrez API (http://biopython.org/DIST/docs/tutorial/Tutorial.html#sec61)

**Comment by nhhaidee** [comment]
Added option to povide `ncbi-accession-id`
https://github.com/nhhaidee/wgscovplot/blob/c0ac757dcb0976e4414d0aae6fc0a2f60de94231/wgscovplot/wgscovplot.py#L142-L150

**Comment by nhhaidee** [comment]
With `--ncbi-accession-id` provided, tool can fetch reference sequence, user don't need to provide option `--ref-sequence`
https://github.com/nhhaidee/wgscovplot/blob/451bb9b2539e0c4590cfd07a08f3ba44bf02beea/wgscovplot/wgscovplot.py#L23-L40
