### ISSUE TITLE
Use Jinja2 tojson filter to transform Python values to JS values

### ISSUE THREAD

**Issue by peterk87** [nhhaidee/wgscovplot#13]
For example, boolean values in JS should be type boolean (`true`/`false`) not string `"True"`/`"False"`:

https://github.com/nhhaidee/wgscovplot/blob/a8b07f67560822d76af0dd54a3717f0a1580b67b/wgscovplot/tmpl/wgscovplot_template.html#L62-L67

https://github.com/nhhaidee/wgscovplot/blob/a8b07f67560822d76af0dd54a3717f0a1580b67b/wgscovplot/tmpl/wgscovplot_template.html#L69-L74

The [tojson](https://jinja.palletsprojects.com/en/3.0.x/templates/#jinja-filters.tojson) Jinja2 filter should be used wherever Python values and to be transformed into JS values:

```js
const geneFeature = {{ gene_feature|tojson }};
// templated as 
const geneFeature = true;
```

**Comment by nhhaidee** [comment]
Updated by commit https://github.com/nhhaidee/wgscovplot/commit/85adebb3032dcd474242b2c53d17392e7637cddb
