### ISSUE TITLE
Non-dev JS dependencies?

### ISSUE THREAD

**Issue by peterk87** [nhhaidee/wgscovplot#30]
The `devDependencies` are listed in the `package.json`, but where are the other dependencies?

https://github.com/nhhaidee/wgscovplot/blob/master/package.json

Both Lodash and ECharts should be regular dependencies
https://github.com/nhhaidee/wgscovplot/blob/d73b55e4fedb8b8b5a9056e502f0e6b61b76ebe1/package.json#L30
https://github.com/nhhaidee/wgscovplot/blob/d73b55e4fedb8b8b5a9056e502f0e6b61b76ebe1/package.json#L32

Select2, jQuery and Bootstrap are missing from `package.json`.

**Comment by nhhaidee** [comment]
@peterk87: updated by PR https://github.com/nhhaidee/wgscovplot/pull/33
